spring:
  application:
    name: sb-demo
  datasource:
    url: jdbc:h2:mem:fmfi
  jpa:
    defer-datasource-initialization: true


app:
  hello:
    greeting: Ahoj
  current-account:
    transaction:
      getLatestCurrentAccountTransactionsMaxRecordCount: 20
  integration:
    fees:
      base-uri: http://localhost:1080
      username: dummy
      password: dummy
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    java:
      enabled: true

